# Generated by Django 6.0.7 on 2026-09-15 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_class',
        ),
        migrations.DeleteModel(
            name='ParentProfile',
        ),
    ]
