# Generated by Django 6.1.1 on 2026-09-11 00:30

import django.db.models.deletion
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('homework', 'Homework'), ('project', 'Project'), ('worksheet', 'Worksheet'), ('reading', 'Reading'), ('class_activity', 'Class Activity'), ('quiz', 'Quiz'), ('revision', 'Revision Task')], default='homework', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('importance', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=1.0, help_text='Estimated completion time, in hours.', max_digits=4)),
                ('max_marks', models.PositiveIntegerField(default=10)),
                ('due_date', models.DateTimeField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to=tasks.models.task_attachment_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='academics.classroom')),
                ('student', models.ForeignKey(blank=True, help_text='Set this to assign the task to a single student instead of a whole class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_tasks', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.teacherprofile')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
